import type { Topic } from '../../../types'

export const numbersTime: Topic = {
  id: 'numbers-time',
  title: 'Числа, время и даты',
  summary: 'Числительные, который час, дни недели и месяцы',
  theory: [
    { type: 'heading', text: 'Числа' },
    {
      type: 'table',
      headers: ['-teen (13–19)', '-ty (десятки)'],
      rows: [
        ['13 thirteen', '30 thirty'],
        ['14 fourteen', '40 forty'],
        ['15 fifteen', '50 fifty'],
        ['16 sixteen', '60 sixty'],
        ['17 seventeen', '70 seventy'],
        ['18 eighteen', '80 eighty'],
        ['19 nineteen', '90 ninety'],
      ],
    },
    {
      type: 'note',
      tone: 'warning',
      text: '**forty** — без u (хотя four). Ударение: thir**TEEN**, но **THIR**ty — так их различают на слух.',
    },
    {
      type: 'examples',
      items: [
        { en: '21 — twenty-one', ru: 'десятки и единицы — через дефис' },
        { en: '100 — a hundred / one hundred' },
        { en: '365 — three hundred and sixty-five', ru: 'в британском варианте после сотен ставится and' },
        { en: '1,000 — a thousand', ru: 'разряды отделяются запятой' },
      ],
    },
    { type: 'heading', text: 'Который час?' },
    {
      type: 'table',
      headers: ['Время', 'Как сказать', 'Проще'],
      rows: [
        ['7:00', "seven o'clock", 'seven'],
        ['7:10', 'ten past seven', 'seven ten'],
        ['7:15', 'quarter past seven', 'seven fifteen'],
        ['7:30', 'half past seven', 'seven thirty'],
        ['7:45', 'quarter to eight', 'seven forty-five'],
        ['7:50', 'ten to eight', 'seven fifty'],
      ],
    },
    {
      type: 'rule',
      text: '**past** — «после» (первая половина часа), **to** — «до» (вторая половина). What time is it? — It’s **half past** six.',
    },
    { type: 'heading', text: 'Дни, месяцы и даты' },
    {
      type: 'paragraph',
      text: 'Дни недели и месяцы всегда пишутся с **заглавной буквы**: Monday, January. Для дат нужны порядковые числительные.',
    },
    {
      type: 'table',
      headers: ['Число', 'Порядковое', 'Сокращение'],
      rows: [
        ['1', 'first', '1st'],
        ['2', 'second', '2nd'],
        ['3', 'third', '3rd'],
        ['4', 'fourth', '4th'],
        ['5', 'fifth', '5th'],
        ['12', 'twelfth', '12th'],
        ['20', 'twentieth', '20th'],
        ['21', 'twenty-first', '21st'],
      ],
    },
    {
      type: 'examples',
      items: [
        { en: 'My birthday is on the 5th of May.', ru: 'Мой день рождения пятого мая.' },
        { en: "What's the date today? — It's the 3rd of June.", ru: 'Какое сегодня число? — Третье июня.' },
      ],
    },
  ],
  cards: [
    { id: 'monday', en: 'Monday', ru: 'понедельник', transcription: '/ˈmʌndeɪ/' },
    { id: 'tuesday', en: 'Tuesday', ru: 'вторник', transcription: '/ˈtjuːzdeɪ/' },
    { id: 'wednesday', en: 'Wednesday', ru: 'среда', transcription: '/ˈwenzdeɪ/' },
    { id: 'thursday', en: 'Thursday', ru: 'четверг', transcription: '/ˈθɜːzdeɪ/' },
    { id: 'friday', en: 'Friday', ru: 'пятница', transcription: '/ˈfraɪdeɪ/' },
    { id: 'saturday', en: 'Saturday', ru: 'суббота', transcription: '/ˈsætədeɪ/' },
    { id: 'sunday', en: 'Sunday', ru: 'воскресенье', transcription: '/ˈsʌndeɪ/' },
    { id: 'january', en: 'January', ru: 'январь', transcription: '/ˈdʒænjuəri/' },
    { id: 'february', en: 'February', ru: 'февраль', transcription: '/ˈfebruəri/' },
    { id: 'march', en: 'March', ru: 'март' },
    { id: 'april', en: 'April', ru: 'апрель', transcription: '/ˈeɪprəl/' },
    { id: 'may', en: 'May', ru: 'май' },
    { id: 'june', en: 'June', ru: 'июнь' },
    { id: 'july', en: 'July', ru: 'июль', transcription: '/dʒuˈlaɪ/' },
    { id: 'august', en: 'August', ru: 'август', transcription: '/ˈɔːɡəst/' },
    { id: 'september', en: 'September', ru: 'сентябрь' },
    { id: 'october', en: 'October', ru: 'октябрь' },
    { id: 'november', en: 'November', ru: 'ноябрь' },
    { id: 'december', en: 'December', ru: 'декабрь' },
  ],
  exercises: [
    {
      id: 'numbers',
      title: 'Напишите словами',
      items: [
        { kind: 'gap', text: '15 = {fifteen}' },
        { kind: 'gap', text: '40 = {forty}' },
        { kind: 'gap', text: '12 = {twelve}' },
        { kind: 'gap', text: '90 = {ninety}' },
        { kind: 'gap', text: '21 = {twenty-one|twenty one}' },
        { kind: 'gap', text: '3rd = the {third}' },
        { kind: 'gap', text: '1st = the {first}' },
      ],
    },
    {
      id: 'time-dates',
      title: 'Время и календарь',
      items: [
        { kind: 'gap', text: "7:30 — It's {half} past seven." },
        { kind: 'gap', text: "8:45 — It's quarter {to} nine." },
        { kind: 'gap', text: "5:15 — It's quarter {past} five." },
        { kind: 'gap', text: 'The day after Friday is {Saturday}.', translation: 'День после пятницы — суббота.' },
        { kind: 'gap', text: 'The month after March is {April}.', translation: 'Месяц после марта — апрель.' },
        {
          kind: 'gap',
          text: 'The last month of the year is {December}.',
          translation: 'Последний месяц года — декабрь.',
        },
      ],
    },
    {
      id: 'choice',
      title: 'Выберите правильный вариант',
      items: [
        {
          kind: 'choice',
          question: '6:15',
          options: ['quarter past six', 'quarter to six', 'half past six'],
          answer: 0,
        },
        {
          kind: 'choice',
          question: '9:50',
          options: ['ten past nine', 'ten to ten', 'ten to nine'],
          answer: 1,
          explanation: 'Без десяти десять — **ten to ten**.',
        },
        { kind: 'choice', question: 'Как пишется 40?', options: ['fourty', 'forty'], answer: 1 },
        { kind: 'choice', question: 'Christmas is ___ December.', options: ['in', 'on', 'at'], answer: 0 },
        {
          kind: 'choice',
          question: 'My birthday is ___ the 10th of July.',
          options: ['in', 'on', 'at'],
          answer: 1,
          explanation: 'С датами — **on**.',
        },
        { kind: 'choice', question: '2nd = ___', options: ['second', 'twoth', 'secondth'], answer: 0 },
      ],
    },
    {
      id: 'order',
      title: 'Соберите предложение',
      items: [
        {
          kind: 'order',
          answer: 'It is half past six.',
          translation: 'Сейчас половина седьмого.',
          distractors: ['to'],
        },
        {
          kind: 'order',
          answer: 'My birthday is in October.',
          translation: 'Мой день рождения в октябре.',
          distractors: ['on'],
        },
        {
          kind: 'order',
          answer: 'The shop is closed on Sundays.',
          translation: 'Магазин закрыт по воскресеньям.',
          distractors: ['in'],
        },
        {
          kind: 'order',
          answer: 'Today is the first of May.',
          translation: 'Сегодня первое мая.',
          distractors: ['one'],
        },
      ],
    },
  ],
}
