import type { Verb } from './types'

export const verbs: Verb[] = [
  { base: 'be', past: 'was/were', participle: 'been', ru: 'быть', level: 'A1' },
  { base: 'have', past: 'had', participle: 'had', ru: 'иметь', level: 'A1' },
  { base: 'do', past: 'did', participle: 'done', ru: 'делать', level: 'A1' },
  { base: 'go', past: 'went', participle: 'gone', ru: 'идти, ехать', level: 'A1' },
  { base: 'come', past: 'came', participle: 'come', ru: 'приходить', level: 'A1' },
  { base: 'see', past: 'saw', participle: 'seen', ru: 'видеть', level: 'A1' },
  { base: 'get', past: 'got', participle: 'got/gotten', ru: 'получать; добираться', level: 'A1' },
  { base: 'make', past: 'made', participle: 'made', ru: 'делать, создавать', level: 'A1' },
  { base: 'take', past: 'took', participle: 'taken', ru: 'брать', level: 'A1' },
  { base: 'give', past: 'gave', participle: 'given', ru: 'давать', level: 'A1' },
  { base: 'know', past: 'knew', participle: 'known', ru: 'знать', level: 'A1' },
  { base: 'think', past: 'thought', participle: 'thought', ru: 'думать', level: 'A1' },
  { base: 'say', past: 'said', participle: 'said', ru: 'сказать', level: 'A1' },
  { base: 'tell', past: 'told', participle: 'told', ru: 'рассказывать, сообщать', level: 'A1' },
  { base: 'eat', past: 'ate', participle: 'eaten', ru: 'есть', level: 'A1' },
  { base: 'drink', past: 'drank', participle: 'drunk', ru: 'пить', level: 'A1' },
  { base: 'sleep', past: 'slept', participle: 'slept', ru: 'спать', level: 'A1' },
  { base: 'buy', past: 'bought', participle: 'bought', ru: 'покупать', level: 'A1' },
  { base: 'write', past: 'wrote', participle: 'written', ru: 'писать', level: 'A1' },
  { base: 'read', past: 'read', participle: 'read', ru: 'читать', level: 'A1' },
  { base: 'speak', past: 'spoke', participle: 'spoken', ru: 'говорить', level: 'A1' },
  { base: 'meet', past: 'met', participle: 'met', ru: 'встречать, знакомиться', level: 'A1' },
  { base: 'sit', past: 'sat', participle: 'sat', ru: 'сидеть', level: 'A1' },
  { base: 'stand', past: 'stood', participle: 'stood', ru: 'стоять', level: 'A1' },
  { base: 'run', past: 'ran', participle: 'run', ru: 'бегать', level: 'A1' },
  { base: 'swim', past: 'swam', participle: 'swum', ru: 'плавать', level: 'A1' },
  { base: 'begin', past: 'began', participle: 'begun', ru: 'начинать', level: 'A1' },
  { base: 'find', past: 'found', participle: 'found', ru: 'находить', level: 'A1' },
  { base: 'leave', past: 'left', participle: 'left', ru: 'уходить, уезжать; оставлять', level: 'A1' },
  { base: 'put', past: 'put', participle: 'put', ru: 'класть, ставить', level: 'A1' },
  { base: 'pay', past: 'paid', participle: 'paid', ru: 'платить', level: 'A1' },
  { base: 'sing', past: 'sang', participle: 'sung', ru: 'петь', level: 'A1' },
  { base: 'wear', past: 'wore', participle: 'worn', ru: 'носить (одежду)', level: 'A1' },
  { base: 'drive', past: 'drove', participle: 'driven', ru: 'водить (машину)', level: 'A1' },
  { base: 'fly', past: 'flew', participle: 'flown', ru: 'летать', level: 'A1' },
  { base: 'forget', past: 'forgot', participle: 'forgotten', ru: 'забывать', level: 'A1' },
  { base: 'understand', past: 'understood', participle: 'understood', ru: 'понимать', level: 'A1' },
  { base: 'feel', past: 'felt', participle: 'felt', ru: 'чувствовать', level: 'A1' },
  { base: 'cost', past: 'cost', participle: 'cost', ru: 'стоить', level: 'A1' },
  { base: 'send', past: 'sent', participle: 'sent', ru: 'отправлять', level: 'A1' },
]
